version: "3.7"

services:
  nanook:
    container_name: nanook
    image: burgrp/nanook@sha256:d9ed5dd0584becc2d1025cad492fb1174f7342b1bb6700eeb5b55dbacdc6d5b8
    privileged: true
    init: true
    restart: always
    volumes:
      - "/dev:/dev"
      - "/data/nanook:/data"
    environment:
      HTTP_PORT: "80"
      I2C_BUS: "hw:0"
      DATA_DIR: "/data"
      TZ: "Europe/Prague"
    ports:
      - 80:80
    #   - 9229:9229
    # labels:
    #   "farm.device.services": "80,9229 debugger"
    labels:
      "farm.device.services": "80"
