version: "3.7"

services:
  nanook:
    container_name: nanook    
    image: defa/nanook@sha256:d0382477e5c00ed5479d16986a3f679067d63e090653cc52f7984c58352b8be2
    privileged: true
    init: true
    restart: always
    volumes:
      - "/dev:/dev"
      - "/data/nanook:/data"
    environment: 
      HTTP_PORT: "80"
      I2C_BUS: "hw:0"
      DATA_DIR: "/data"
    ports:
      - "80:80"
    labels:
      "farm.device.service": "private nanook 80"
