version: "3.7"

services:
  nanook:
    container_name: nanook    
    image: burgrp/nanook@sha256:1da409213f3fda54cce24b4656ef7cfad90f6281b0883ccffbe4c1c5b21563e0
    privileged: true
    init: true
    restart: always
    volumes:
      - "/dev:/dev"
      - "/data/nanook:/data"
    environment: 
      HTTP_PORT: "80"
      I2C_BUS: "hw:0"
      DATA_DIR: "/data"
      TZ: "Europe/Prague"
    ports:
      - 80:80
    #   - 9229:9229
    # labels:
    #   "farm.device.services": "80,9229 debugger"
    labels:
      "farm.device.services": "80"
