version: "3.7"

services:
  nanook:
    container_name: nanook    
    image: defa/nanook@sha256:fed925eccb55767fe691c508f524d4bf72b2b4273ea547c08aa09fa3e7aa6131
    privileged: true
    init: true
    restart: always
    volumes:
      - "/dev:/dev"
      - "/data/nanook:/data"
    environment: 
      HTTP_PORT: "80"
      I2C_BUS: "hw:0"
      DATA_DIR: "/data"
    ports:
      - "80:80"
    labels:
      "farm.device.service": "private nanook 80"
