version: "3.7"

services:
  nanook:
    container_name: nanook    
    image: defa/nanook@sha256:cec8f1d0b1b80101dcee93f79a44816d04f64f1a5d7197afe9379a2819e2f22e
    privileged: true
    init: true
    restart: always
    volumes:
      - "/dev:/dev"
      - "/data/nanook:/data"
    environment: 
      HTTP_PORT: "80"
      I2C_BUS: "hw:0"
      DATA_DIR: "/data"
    ports:
      - "80:80"
    labels:
      "farm.device.service": "private nanook 80"
